Description: Create a VPC and Linux/Windows EC2 instances - By Uriel Ramirez
Mappings:
  AmazonLinux2Map:
    us-east-1:
      AMI: ami-013be31976ca2c322
    us-east-2:
      AMI: ami-0350c5670171b5391
    us-west-1:
      AMI: ami-01beb64058d271bc4
    us-west-2:
      AMI: ami-061e7ebbc234015fe
  Windows2012Map:
    us-east-1:
      AMI: ami-0e3fbebfa69d4c85c
    us-east-2:
      AMI: ami-08c44c744ddf87622
    us-west-1:
      AMI: ami-0018c07a5ca79359d
    us-west-2:
      AMI: ami-0395238cb927001d5
  Windows2016Map:
    us-east-1:
      AMI: ami-0bf148826ef491d16
    us-east-2:
      AMI: ami-08b4a0f6e106c1dba
    us-west-1:
      AMI: ami-08838e38cfe4854ad
    us-west-2:
      AMI: ami-017bf00eb0d4c7182
Outputs:
  PublicSubnetId1:
    Description: PublicSubnetId1
    Export:
      Name: !Sub '${AWS::StackName}-public-subnet-id-1'
    Value: !Ref 'PublicSubnet1'
  PublicSubnetId2:
    Description: PublicSubnetId2
    Export:
      Name: !Sub '${AWS::StackName}-public-subnet-id-2'
    Value: !Ref 'PublicSubnet2'
  VpcId:
    Description: VpcId
    Export:
      Name: !Sub '${AWS::StackName}-vpc-id'
    Value: !Ref 'Vpc'
Parameters:
  CidrBlockPublicSubnet1:
    AllowedPattern: ((\d{1,3})\.){3}\d{1,3}/\d{1,2}
    Default: 10.0.0.0/24
    Description: Cidr block for the public subnet 1.
    Type: String
  CidrBlockPublicSubnet2:
    AllowedPattern: ((\d{1,3})\.){3}\d{1,3}/\d{1,2}
    Default: 10.0.1.0/24
    Description: Cidr block for the public subnet 2.
    Type: String
  CidrBlockVpc:
    AllowedPattern: ((\d{1,3})\.){3}\d{1,3}/\d{1,2}
    Default: 10.0.0.0/16
    Description: Cidr block for the VPC.
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH and RDP access to the
      instance
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  AmazonLinux2Instance:
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: 'true'
            VolumeSize: 8
            VolumeType: gp2
      IamInstanceProfile: !Ref 'LinuxInstanceProfile'
      ImageId: !FindInMap
        - AmazonLinux2Map
        - !Ref 'AWS::Region'
        - AMI
      InstanceType: t2.micro
      KeyName: !Ref 'KeyName'
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: 0
          GroupSet:
            - !Ref 'LinuxSecurityGroup'
          SubnetId: !Ref 'PublicSubnet1'
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref 'AWS::StackName'
              - -AmazonLinux2
        - Key: Patch Group
          Value: AmazonLinux2
      UserData: !Base64
        Fn::Join:
          - ''
          - - "#!/bin/bash -xe\n"
    Type: AWS::EC2::Instance
  AttachGateway:
    Properties:
      InternetGatewayId: !Ref 'InternetGateway'
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::VPCGatewayAttachment
  IGRoute:
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'InternetGateway'
      RouteTableId: !Ref 'PublicRouteTable'
    Type: AWS::EC2::Route
  InternetGateway:
    Properties:
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
    Type: AWS::EC2::InternetGateway
  LinuxInstanceProfile:
    Properties:
      Roles:
        - !Ref 'LinuxRole'
    Type: AWS::IAM::InstanceProfile
  LinuxRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole
    Type: AWS::IAM::Role
  LinuxSecurityGroup:
    Properties:
      GroupDescription: EC2 Instance Security Group
      GroupName: !Join
        - ''
        - - !Ref 'AWS::StackName'
          - -Linux
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          FromPort: '22'
          IpProtocol: tcp
          ToPort: '22'
        - CidrIp: '0.0.0.0/0'
          FromPort: '80'
          IpProtocol: tcp
          ToPort: '80'
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::SecurityGroup
  PublicRouteTable:
    Properties:
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: public
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::RouteTable
  PublicSubnet1:
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      CidrBlock: !Ref 'CidrBlockPublicSubnet1'
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: public-subnet-1
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::Subnet
  PublicSubnet1RouteTableAssociation:
    Properties:
      RouteTableId: !Ref 'PublicRouteTable'
      SubnetId: !Ref 'PublicSubnet1'
    Type: AWS::EC2::SubnetRouteTableAssociation
  PublicSubnet2:
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      CidrBlock: !Ref 'CidrBlockPublicSubnet2'
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: public-subnet-2
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::Subnet
  PublicSubnet2RouteTableAssociation:
    Properties:
      RouteTableId: !Ref 'PublicRouteTable'
      SubnetId: !Ref 'PublicSubnet2'
    Type: AWS::EC2::SubnetRouteTableAssociation
  Vpc:
    Properties:
      CidrBlock: !Ref 'CidrBlockVpc'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
    Type: AWS::EC2::VPC
  Windows2012Instance:
    Properties:
      IamInstanceProfile: !Ref 'WindowsInstanceProfile'
      ImageId: !FindInMap
        - Windows2012Map
        - !Ref 'AWS::Region'
        - AMI
      InstanceType: t2.medium
      KeyName: !Ref 'KeyName'
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: 0
          GroupSet:
            - !Ref 'WindowsSecurityGroup'
          SubnetId: !Ref 'PublicSubnet1'
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref 'AWS::StackName'
              - -Windows2012
    Type: AWS::EC2::Instance
  Windows2016Instance:
    Properties:
      IamInstanceProfile: !Ref 'WindowsInstanceProfile'
      ImageId: !FindInMap
        - Windows2016Map
        - !Ref 'AWS::Region'
        - AMI
      InstanceType: t2.medium
      KeyName: !Ref 'KeyName'
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: 0
          GroupSet:
            - !Ref 'WindowsSecurityGroup'
          SubnetId: !Ref 'PublicSubnet1'
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref 'AWS::StackName'
              - -Windows2016
    Type: AWS::EC2::Instance
  WindowsInstanceProfile:
    Properties:
      Roles:
        - !Ref 'WindowsRole'
    Type: AWS::IAM::InstanceProfile
  WindowsRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole
    Type: AWS::IAM::Role
  WindowsSecurityGroup:
    Properties:
      GroupDescription: EC2 Instance Security Group
      GroupName: !Join
        - ''
        - - !Ref 'AWS::StackName'
          - -Windows
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          FromPort: '3389'
          IpProtocol: tcp
          ToPort: '3389'
        - CidrIp: '0.0.0.0/0'
          FromPort: '80'
          IpProtocol: tcp
          ToPort: '80'
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::SecurityGroup

